AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - .gems/**/*
    - spec/rails_helper.rb
    - Rakefile
    - Gemfile
    - config.ru
    - test/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolProc:
  Enabled: false